version: "3.9"
name: ride-hailing-system

services:
  database:
    image: postgres:15
    container_name: ride_hailing_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    networks:
      - ride_hailing_network

  booking_service:
    build:
      context: ./
      dockerfile: ./booking-service/Dockerfile
    container_name: booking_service
    environment:
      DB_HOST: database
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      SERVICE_PORT: 80
    depends_on:
      - database
    ports:
      - "8092:80"
    networks:
      - ride_hailing_network

  ride_service:
    build:
      context: ./
      dockerfile: ./ride-service/Dockerfile
    container_name: ride_service
    environment:
      DB_HOST: database
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      SERVICE_PORT: 80
    depends_on:
      - database
    ports:
      - "8088:80"
    networks:
      - ride_hailing_network

  user_service:
    build:
      context: ./
      dockerfile: ./user-service/Dockerfile
    container_name: user_service
    environment:
      DB_HOST: database
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      SERVICE_PORT: 80
    depends_on:
      - database
    ports:
      - "8090:80"
    networks:
      - ride_hailing_network

volumes:
  db_data:

networks:
  ride_hailing_network:
